Repository Mugunth-dev/Hacktoberfest2024, pull requests merged in 2024-10, with the labels that each got.

#25 Implement Various Utility Functions and Add Robust Input Handling
  python/LongSubString.py
  python/Palindrome.py
  python/ReverseWords.py
  python/armstrong.py
  python/fibonacci.py
  python/palindrome-checker.py
  python/primeNumber.py
  python/sumOfUniqueElements.py
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create QR_code_Generator.py
  python/QR_code_Generator.py
Labels: hacktoberfest

#33 #29 pygame added Number Guessing Game
  pygames/Number Guessing Game/README.md
  pygames/Number Guessing Game/main.py
Labels: enhancement, hacktoberfest

#34 Create Dino Games on pygames directory
  pygames/Dino_Game/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added basic calculator
  python/Basic Calculator.py
Labels: good first issue, hacktoberfest

#36 hangman.py
  python/hangman.py
Labels: good first issue, hacktoberfest

#40 Pygames added
  pygames/Rock, Paper, Scissors/main.py
Labels: hacktoberfest

#35 #16 Binary Search in a sorted array
  DSA in python/algorithms/binary_search.py
  DSA in python/tests/test_algorithms.py
  DSA in python/tests/test_data_structures.py
Labels: hacktoberfest

#39 Added Binary Search in Sorted Array Code
  DSA in python/algorithms/binarySearch.py
Labels: hacktoberfest
